"""
Django settings for monkey project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import logging.handlers
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qm-pnmr&6oatsriq#qis+%11fraax_cde@o6@qe7is-6fw^lmf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["10.218.139.208","localhost","127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'slot_booking',
    'splunkparser',
    'binblock',
    'pdf_merger',
    'gen_reversals',
    'astrex_html_logs',
    'emvco_logs',
    'validate_testcases',
    'splunkrrn',
    'runquery',
    'compare',
    'yaml2json',
    'xlog_mastercard',
    'certifications',
    'hex2iso',
    'json2sql',
    'ascii2hex',
    'junglewire'
]

LOG_DIR = BASE_DIR / 'logs'
os.makedirs(LOG_DIR, exist_ok=True)  # Ensure log folder exists

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'django.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 0,
            'formatter': 'standard',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'loggers': {
        '': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True
        },
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'monkey.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'html'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'monkey.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Define the path to the Oracle Instant Client libraries
ORACLE_CLIENT_PATH = r'C:\Oracle\Ora12c_64\BIN'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'local_oracle': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'localhost:1521/freepdb1',  # lowercase to match service name
        'USER': 'oasis77',
        'PASSWORD': 'your_password',
        'client_path': None  # or set your Oracle Client path if using thick mode
    },
    'dr_ist': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'A4PCDO8001.ESH.PAR_IST',
        'USER': 'F94GDOS',
        'PASSWORD': 'Ireland2025!',
        'HOST': '',
        'PORT': '',
        'client_path': ORACLE_CLIENT_PATH,
        'owner': 'OASIS77', 

    },
    'dr_novate': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'A4PCDO8001.ESH.PAR_IST',
        'USER': 'F94GDOS',
        'PASSWORD': 'Ireland2025!',
        'HOST': '',
        'PORT': '',
        'client_path': ORACLE_CLIENT_PATH,
        'owner': 'NOVATE',  
    },
    'prod_ist': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'A5PCDO8001.EQU.IST',
        'USER': 'F94GDOS',
        'PASSWORD': 'Ireland2025!',
        'HOST': '',
        'PORT': '',
        'client_path': ORACLE_CLIENT_PATH,
        'owner': 'OASIS77', 
    },
    'prod_novate': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'A5PCDO8001.EQU.IST',
        'USER': 'F94GDOS',
        'PASSWORD': 'Ireland2025!',
        'HOST': '',
        'PORT': '',
        'client_path': ORACLE_CLIENT_PATH,
        'owner': 'NOVATE',  

    },
    'uat_ist': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'ISTU2_EQU',
        'USER': 'oasis77',
        'PASSWORD': 'ist0py',
        'HOST': '',
        'PORT': '',
        'client_path': ORACLE_CLIENT_PATH,
    },
    'uat_novate': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'ISTU2_EQU',
        'USER': 'novate',
        'PASSWORD': 'nov1234',
        'HOST': '',
        'PORT': '',
        'client_path': ORACLE_CLIENT_PATH,
    },
    'uat_novate_conf': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'ISTU2_EQU',
        'USER': 'novate_conf',
        'PASSWORD': 'nov1234',
        'HOST': '',
        'PORT': '',
        'client_path': ORACLE_CLIENT_PATH,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "home/static",
    BASE_DIR / "splunkparser/static",
    BASE_DIR / "binblock/static",
    BASE_DIR / "slot_booking/static",
    BASE_DIR / "gen_reversals/static",
    BASE_DIR / "astrex_html_logs/static",
    BASE_DIR / "emvco_logs/static",
    BASE_DIR / "runquery/static",
    BASE_DIR / "validate_testcases/static",
    BASE_DIR / "splunkrrn/static",
    BASE_DIR / "pdf_merger/static",
    BASE_DIR / "compare/static",
    BASE_DIR / "yaml2json/static",
    BASE_DIR / "xlog_mastercard/static",
    BASE_DIR / "certifications/static",
    BASE_DIR / "hex2iso/static",
    BASE_DIR / "json2sql/static",
    BASE_DIR / "junglewire/static",

    


    
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
